# Generated by Django 6.0.2 on 2026-02-26 20:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('platform', models.CharField(choices=[('Google Ads', 'Google Ads'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('Email', 'Email')], max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Paused', 'Paused'), ('Completed', 'Completed'), ('Draft', 'Draft')], default='Draft', max_length=50)),
                ('budget', models.FloatField()),
                ('amount_spent', models.FloatField(default=0.0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_audience', models.TextField(blank=True, null=True)),
                ('goal', models.CharField(choices=[('Brand Awareness', 'Brand Awareness'), ('Lead Generation', 'Lead Generation'), ('Sales', 'Sales'), ('Traffic', 'Traffic'), ('Engagement', 'Engagement')], max_length=50)),
                ('roi', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
