# Generated by Django 6.0.2 on 2026-02-26 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('spend', models.FloatField(default=0.0)),
                ('revenue', models.FloatField(default=0.0)),
                ('roi', models.FloatField(default=0.0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_performances', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['month'],
                'unique_together': {('campaign', 'month')},
            },
        ),
    ]
